//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGORM.CodeBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelperResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelperResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PGORM.CodeBuilder.HelperResources", typeof(HelperResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract
        ///as
        ///base
        ///bool
        ///break
        ///byte
        ///case
        ///catch
        ///char
        ///checked
        ///class
        ///const
        ///continue
        ///decimal
        ///default
        ///delegate
        ///do
        ///double
        ///else
        ///enum
        ///event
        ///explicit
        ///extern
        ///false
        ///finally
        ///fixed
        ///float
        ///for
        ///foreach
        ///from
        ///get
        ///goto
        ///group
        ///if
        ///implicit
        ///in
        ///int
        ///interface
        ///internal
        ///into
        ///is
        ///join
        ///let
        ///lock
        ///long
        ///namespace
        ///new
        ///null
        ///object
        ///operator
        ///orderby
        ///out
        ///override
        ///params
        ///partial
        ///partial
        ///private
        ///protected
        ///public
        ///readonly
        ///ref
        ///return
        ///sbyte
        ///sealed
        ///select
        ///set
        ///short
        ///sizeof
        ///stackalloc
        ///sta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReservedWords {
            get {
                return ResourceManager.GetString("ReservedWords", resourceCulture);
            }
        }
    }
}
