//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBuilder.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///assembly_info(asm) ::=&lt;&lt;
        ///using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// General Information about an assembly is controlled through the following 
        ///// set of attributes. Change these attribute values to modify the information
        ///// associated with an assembly.
        ///[assembly: AssemblyTitle(&quot;&lt;asm.Title&gt;&quot;)]
        ///[assembly: AssemblyDescription(&quot;&lt;asm.Description&gt;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&lt;asm.Configuration&gt;&quot;)]
        ///[assembly: Assembly [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyInfo_stg {
            get {
                return ResourceManager.GetString("AssemblyInfo_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///usings(lib) ::=&lt;&lt;
        ///using &lt;lib&gt;;
        ///&gt;&gt;
        ///
        ///dataobject(libs,namespace,table,properties) ::=&lt;&lt;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Reflection;
        ///&lt;libs:usings(); separator=&quot;\r\n&quot;&gt;
        ///
        ///namespace &lt;namespace&gt;
        ///{
        ///	#region &lt;table.TemplateRelationName&gt;
        ///	public class &lt;table.TemplateRelationName&gt; : DataObjectBase
        ///	{
        ///		#region ctor
        ///		public &lt;table.TemplateRelationName&gt;()
        ///		{
        ///		}
        ///		#endregi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataObject_stg {
            get {
                return ResourceManager.GetString("DataObject_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///usings(lib) ::=&lt;&lt;
        ///using &lt;lib&gt;;
        ///&gt;&gt;
        ///
        ///recordset(libs,namespace,table) ::=&lt;&lt;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Reflection;
        ///&lt;libs:usings(); separator=&quot;\r\n&quot;&gt;
        ///
        ///namespace &lt;namespace&gt;.RecordSet
        ///{	
        ///	#region &lt;table.RecordsetName&gt;
        ///	public class &lt;table.RecordsetName&gt; : DataObjectRecordSetBase\&lt;&lt;table.TemplateRelationName&gt;\&gt;
        ///	{
        ///		#region FromList
        ///		public static &lt;table.Recordse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataObjectRecordSet_stg {
            get {
                return ResourceManager.GetString("DataObjectRecordSet_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to factory(libs,namespace,table,methods) ::=&lt;&lt;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Reflection;
        ///using System.Diagnostics;
        ///using Npgsql;
        ///&lt;libs:usings(); separator=&quot;\r\n&quot;&gt;
        ///
        ///namespace &lt;namespace&gt;.Factory
        ///{
        ///	#region &lt;table.FactoryName&gt;
        ///	&lt;code_summary({Factory class for relation &lt;table.RelationName&gt;})&gt;
        ///	public class &lt;table.FactoryName&gt;
        ///	{
        ///		&lt;methods; separator=&quot;\r\n&quot;&gt;
        ///		#region CreateFromRea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Factory_Factory_stg {
            get {
                return ResourceManager.GetString("Factory_Factory_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get_method(table,method_name,icolumns,sep_comma,summary) ::=&lt;&lt;
        ///#region getall_method
        ///&lt;summary&gt;
        ///&lt;intelli_tans()&gt;
        ///&lt;intelli_param_sort_page()&gt;
        ///&lt;intelli_type_param_list(table)&gt;
        ///&lt;intelli_type_param_table(table)&gt;
        ///&lt;icolumns:intelli_param_column(); separator=&quot;\r\n&quot;&gt;
        ///&lt;intelli_returns_table_list()&gt;
        ///public static R &lt;method_name&gt;&lt;generic(&quot;T,R&quot;)&gt;(&lt;create_parameters(icolumns)&gt;&lt;sep_comma&gt;NpgsqlTransaction p_Transaction,SortOperation p_SortOperation,PagingOperation p_PagingOperation) where T : &lt;table.TemplateRelat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Factory_GetManyBy_stg {
            get {
                return ResourceManager.GetString("Factory_GetManyBy_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getby_single_return_method(table,icolumns,index) ::=&lt;&lt;
        ///#region getby_single_return_method
        ///&lt;code_summary({Returns a single object of type [&lt;table.TemplateRelationName&gt;] based on [&lt;index.IndexType&gt; / &lt;index.Indexname&gt;].})&gt;
        ///&lt;icolumns:intelli_param_column(); separator=&quot;\r\n&quot;&gt;
        ///&lt;intelli_tans()&gt;
        ///&lt;intelli_type_param_table(table)&gt;
        ///&lt;intelli_returns_table(table)&gt;
        ///public static T &lt;create_getby_method_name(icolumns)&gt;&lt;generic(&quot;T&quot;)&gt;(&lt;create_parameters(icolumns)&gt;,NpgsqlTransaction p_Transaction) where T : &lt;table.Tem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Factory_GetSingle_stg {
            get {
                return ResourceManager.GetString("Factory_GetSingle_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert_method(table) ::=&lt;&lt;
        ///#region insert_method
        ///&lt;code_summary({Inserts a new record into table [&lt;table.RelationName&gt;] based on an object 
        ////// of type &lt;table.TemplateRelationName&gt;. This method updates the [ref p_&lt;table.TemplateRelationName&gt;]
        ////// with the latest affected column values.})&gt;
        ///&lt;intelli_param(name={p_&lt;table.TemplateRelationName&gt;},desc={A ref object of type &lt;table.TemplateRelationName&gt;.})&gt;
        ///&lt;intelli_type_param_table(table)&gt;
        ///public static void Insert\&lt;T\&gt;(ref T p_&lt;table.TemplateRelationName&gt;)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Factory_InsertInto_stg {
            get {
                return ResourceManager.GetString("Factory_InsertInto_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///
        ///usings(lib) ::=&lt;&lt;
        ///using &lt;lib&gt;;
        ///&gt;&gt;
        ///
        ///intelli_returns(text) ::=&quot;/// \&lt;returns\&gt;&lt;text&gt;\&lt;/returns\&gt;&quot;
        ///
        ///intelli_returns_table(table) ::=&quot;/// \&lt;returns\&gt;An object of type [&lt;table.TemplateRelationName&gt;].\&lt;/returns\&gt;&quot;
        ///intelli_returns_table_list(table) ::=&quot;/// \&lt;returns\&gt;A list of List&amp;lt;&lt;table.TemplateRelationName&gt;&amp;gt; of type [&lt;table.TemplateRelationName&gt;].\&lt;/returns\&gt;&quot;
        ///
        ///intelli_type_param_table(table) ::=&lt;&lt;
        ////// \&lt;typeparam name=&quot;T&quot;\&gt;A class of type [&lt;table.TemplateRelationName&gt;]. The (de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Factory_Main_stg {
            get {
                return ResourceManager.GetString("Factory_Main_stg", resourceCulture);
            }
        }
    }
}
