//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBuilder.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///assembly_info(asm) ::=&lt;&lt;
        ///using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// General Information about an assembly is controlled through the following 
        ///// set of attributes. Change these attribute values to modify the information
        ///// associated with an assembly.
        ///[assembly: AssemblyTitle(&quot;&lt;asm.Title&gt;&quot;)]
        ///[assembly: AssemblyDescription(&quot;&lt;asm.Description&gt;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&lt;asm.Configuration&gt;&quot;)]
        ///[assembly: Assembly [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyInfo_stg {
            get {
                return ResourceManager.GetString("AssemblyInfo_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///usings(lib) ::=&lt;&lt;
        ///using &lt;lib&gt;;
        ///&gt;&gt;
        ///
        ///dataobject(libs,namespace,table,properties) ::=&lt;&lt;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Reflection;
        ///&lt;libs:usings(); separator=&quot;\r\n&quot;&gt;
        ///
        ///namespace &lt;namespace&gt;
        ///{
        ///	#region &lt;table.TemplateRelationName&gt;
        ///	public class &lt;table.TemplateRelationName&gt; : DataObjectBase
        ///	{
        ///		#region Static Properties
        ///		public static readonly string RELATION_NAME =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataObject_stg {
            get {
                return ResourceManager.GetString("DataObject_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///usings(lib) ::=&lt;&lt;
        ///using &lt;lib&gt;;
        ///&gt;&gt;
        ///
        ///factory(libs,namespace,table,getby_methods,dml_functions) ::=&lt;&lt;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Reflection;
        ///using System.Diagnostics;
        ///&lt;libs:usings(); separator=&quot;\r\n&quot;&gt;
        ///
        ///namespace &lt;namespace&gt;.Factory
        ///{
        ///	#region &lt;table.FactoryName&gt;
        ///	public class &lt;table.FactoryName&gt;
        ///	{
        ///		&lt;dml_functions; separator=&quot;\r\n&quot;&gt;
        ///		&lt;getby_methods; separato [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataObjectFactory_stg {
            get {
                return ResourceManager.GetString("DataObjectFactory_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///usings(lib) ::=&lt;&lt;
        ///using &lt;lib&gt;;
        ///&gt;&gt;
        ///
        ///recordset(libs,namespace,table) ::=&lt;&lt;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Reflection;
        ///&lt;libs:usings(); separator=&quot;\r\n&quot;&gt;
        ///
        ///namespace &lt;namespace&gt;.RecordSet
        ///{	
        ///	#region &lt;table.RecordsetName&gt;
        ///	public class &lt;table.RecordsetName&gt; : DataObjectRecordSetBase\&lt;&lt;table.TemplateRelationName&gt;\&gt;
        ///	{
        ///		#region FromList
        ///		public static &lt;table.Recordse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataObjectRecordSet_stg {
            get {
                return ResourceManager.GetString("DataObjectRecordSet_stg", resourceCulture);
            }
        }
    }
}
