//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGORM.CodeBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataAccessProjectFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAccessProjectFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PGORM.CodeBuilder.DataAccessProjectFiles", typeof(DataAccessProjectFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // NpgsqlTypes\ArrayHandling.cs
        /////
        ///// Author:
        /////    Jon Hanna. (jon@hackcraft.net)
        /////
        /////    Copyright (C) 2007-2008 The Npgsql Development Team
        /////    npgsql-general@gborg.postgresql.org
        /////    http://gborg.postgresql.org/project/npgsql/projdisplay.php
        /////
        ///// Permission to use, copy, modify, and distribute this software and its
        ///// documentation for any purpose, without fee, and without a written
        ///// agreement is hereby granted, provided that the above copyright notice
        ///// and this paragraph and the f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArrayHandling {
            get {
                return ResourceManager.GetString("ArrayHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using Npgsql;
        ///using System.Data.Common;
        ///using System.Data;
        ///
        ///namespace TemplateNS.Core
        ///{
        ///    #region ObjectRelationMapper
        ///    public delegate T ObjectRelationMapper&lt;T&gt;(IDataReader reader);
        ///    #endregion
        ///
        ///    #region DbINParameter
        ///    public class DbINParameter&lt;T&gt; : DbParameter
        ///    {
        ///        private string p_param_name;
        ///        private string p_param_value;
        ///        public DbINParameter(string parameter_na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataAccess {
            get {
                return ResourceManager.GetString("DataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.ComponentModel;
        ///using System.Data.Common;
        ///
        ///namespace TemplateNS.Core
        ///{
        ///    #region CompareOption
        ///    public enum CompareOption
        ///    {
        ///        Equals,
        ///        Like,
        ///        ILike
        ///    }
        ///    #endregion
        ///
        ///    #region OperationParameter
        ///    public class OperationParameter
        ///    {
        ///        #region Props
        ///        public string ColumnName { get; set; }
        ///        public string ParameterName { get; set; } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DatabaseOperation {
            get {
                return ResourceManager.GetString("DatabaseOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace TemplateNS.Core
        ///{
        ///    #region EntityStatus
        ///    public enum EntityStatus
        ///	{
        ///		Default,
        ///		Changed,
        ///		New,
        ///		Deleted,
        ///        ChangeMany
        ///	}
        ///	#endregion
        ///	
        ///	#region DataObjectBase
        ///    public class DataObjectBase
        ///    {
        ///        public EntityStatus EntityStatus { get; set; }
        ///
        ///        public DataObjectBase()
        ///		{
        ///            EntityStatus = EntityStatus.New;
        ///		}
        ///    }
        ///    #endregion
        ///}
        ///.
        /// </summary>
        internal static string DataObjectBase {
            get {
                return ResourceManager.GetString("DataObjectBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.ComponentModel;
        ///
        ///namespace TemplateNS.Core
        ///{    
        ///    #region DataObjectRecordSetBase
        ///    public class DataObjectRecordSetBase&lt;T&gt; : List&lt;T&gt; where T : DataObjectBase
        ///    {
        ///    }
        ///    #endregion
        ///}.
        /// </summary>
        internal static string DataObjectRecordSetBase {
            get {
                return ResourceManager.GetString("DataObjectRecordSetBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.ComponentModel;
        ///
        ///namespace TemplateNS.Core
        ///{
        ///    #region DataObjectValue
        ///    [DefaultProperty(&quot;Value&quot;)]
        ///    public class DataObjectValue&lt;T&gt;
        ///    {
        ///        #region props
        ///        private object _value;
        ///        #endregion
        ///
        ///        public Type Converter;
        ///
        ///        #region DbValue
        ///        public object DbValue
        ///        {
        ///            get
        ///            {
        ///				return _value;
        ///            }
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataObjectValue {
            get {
                return ResourceManager.GetString("DataObjectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.ComponentModel;
        ///
        ///namespace TemplateNS.Core
        ///{
        ///	#region Helper
        ///	public class Helper
        ///	{
        ///		public static readonly string SQL_SELECT = &quot;SELECT * FROM {0} {1}&quot;;
        ///		public static readonly string SQL_SELECT_COUNT = &quot;SELECT COUNT(*) FROM {0}&quot;;
        ///		public static readonly string SQL_SELECT_WHERE = &quot;SELECT {0} FROM {1} WHERE {2} {3}&quot;;
        ///		public static readonly string SQL_INSERT_INTO = &quot;INSERT INTO {0} ({1}) VALU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Helper {
            get {
                return ResourceManager.GetString("Helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace TemplateNS.Core
        ///{
        ///    public interface IPostgreSQLTypeConverter
        ///    {
        ///        object FromString(string data);
        ///        string ToString(object obj);
        ///        string PgType();
        ///        string PgTypeSchema();
        ///        Type CLRType();
        ///    }
        ///
        ///    [AttributeUsageAttribute(AttributeTargets.Class)]
        ///    public class PostgreSQLTypeConverterAttribute : Attribute
        ///    {
        ///    }
        ///
        ///    public delegate void Schema [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostgreSQLTypeConverter {
            get {
                return ResourceManager.GetString("PostgreSQLTypeConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections;
        ///using System.Linq;
        ///using System.Text;
        ///using System.IO;
        ///
        ///namespace TemplateNS.Core
        ///{
        ///    public class StringSplitter
        ///    {
        ///        #region Properties
        ///        private TextReader stream;
        ///        private bool EOS = false;
        ///        private bool EOL = false;
        ///        private char[] buffer = new char[8192];
        ///        private int pos = 0;
        ///        private int length = 0;
        ///        private char delimiter;
        ///        #endregion
        ///
        ///        public static object[] Split(st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringSplitter {
            get {
                return ResourceManager.GetString("StringSplitter", resourceCulture);
            }
        }
    }
}
