//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGORM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PGORM.CodeTemplates", typeof(CodeTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///assembly_info(project,project_guid) ::=&lt;&lt;
        ///using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// General Information about an assembly is controlled through the following 
        ///// set of attributes. Change these attribute values to modify the information
        ///// associated with an assembly.
        ///[assembly: AssemblyTitle(&quot;&lt;project.RootNamespace&gt;&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyInfo_stg {
            get {
                return ResourceManager.GetString("AssemblyInfo_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///usings(lib) ::=&lt;&lt;
        ///using &lt;lib&gt;;
        ///&gt;&gt;
        ///
        ///dataobject(libs,namespace,table,properties) ::=&lt;&lt;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Reflection;
        ///&lt;libs:usings(); separator=&quot;\r\n&quot;&gt;
        ///
        ///namespace &lt;namespace&gt;
        ///{
        ///	#region &lt;table.TemplateTableName&gt;
        ///	public class &lt;table.TemplateTableName&gt; : DbObjectBase
        ///	{
        ///		#region Static Properties
        ///		public static readonly string TABLE_NAME = &quot;\&quot;&lt;table.T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataObject_stg {
            get {
                return ResourceManager.GetString("DataObject_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///usings(lib) ::=&lt;&lt;
        ///using &lt;lib&gt;;
        ///&gt;&gt;
        ///
        ///factory(libs,namespace,table,getby_methods,dml_functions) ::=&lt;&lt;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Reflection;
        ///&lt;libs:usings(); separator=&quot;\r\n&quot;&gt;
        ///
        ///namespace &lt;namespace&gt;
        ///{
        ///	#region &lt;table.FactoryName&gt;
        ///	public class &lt;table.FactoryName&gt;
        ///	{
        ///		&lt;dml_functions; separator=&quot;\r\n&quot;&gt;
        ///		&lt;getby_methods; separator=&quot;\r\n&quot;&gt;
        ///		#region CreateFromRead [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataObjectFactory_stg {
            get {
                return ResourceManager.GetString("DataObjectFactory_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///usings(lib) ::=&lt;&lt;
        ///using &lt;lib&gt;;
        ///&gt;&gt;
        ///
        ///recordset(libs,namespace,table) ::=&lt;&lt;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Reflection;
        ///&lt;libs:usings(); separator=&quot;\r\n&quot;&gt;
        ///
        ///namespace &lt;namespace&gt;
        ///{	
        ///	#region &lt;table.RecordsetName&gt;
        ///	public class &lt;table.RecordsetName&gt; : DbRecordSetBase\&lt;&lt;table.TemplateTableName&gt;\&gt;
        ///	{
        ///		#region FromList
        ///		public static &lt;table.RecordsetName&gt; FromList(List\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataObjectRecordSet_stg {
            get {
                return ResourceManager.GetString("DataObjectRecordSet_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///create_stored_function(libs,namespace,functions) ::=&lt;&lt;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Reflection;
        ///&lt;libs:usings(); separator=&quot;\r\n&quot;&gt;
        ///
        ///namespace &lt;namespace&gt;
        ///{
        ///	public class StoredProcedures
        ///	{
        ///		&lt;functions; separator=&quot;\r\n&quot;&gt;
        ///	}
        ///}
        ///&gt;&gt;
        ///
        ///create_composite_set_returning(function,returntype,args) ::=&lt;&lt;
        ///#region &lt;function.FunctionName&gt;
        ///public static &lt;returntype&gt; &lt;function [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Function_stg {
            get {
                return ResourceManager.GetString("Function_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///helper(namespace) ::=&lt;&lt;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.ComponentModel;
        ///
        ///namespace &lt;namespace&gt;
        ///{
        ///	#region Helper
        ///	public class Helper
        ///	{
        ///		public static readonly string SQL_SELECT = &quot;SELECT * FROM {0} {1}&quot;;
        ///		public static readonly string SQL_SELECT_COUNT = &quot;SELECT COUNT(*) FROM {0}&quot;;
        ///		public static readonly string SQL_SELECT_WHERE = &quot;SELECT {0} FROM {1} WHERE {2} {3}&quot;;
        ///		public static readonly string SQL_INSER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelperClasses_stg {
            get {
                return ResourceManager.GetString("HelperClasses_stg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group main;
        ///
        ///cs_project(projectGuid,project,compile_items,project_refs,compile_output_folder) ::= &lt;&lt;\&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?\&gt;
        ///\&lt;Project ToolsVersion=&quot;3.5&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;\&gt;
        ///  \&lt;PropertyGroup\&gt;
        ///    \&lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;\&gt;Debug\&lt;/Configuration\&gt;
        ///    \&lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;\&gt;AnyCPU\&lt;/Platform\&gt;
        ///    \&lt;ProductVersion\&gt;9.0.30729\&lt;/ProductVersion\&gt;
        ///    \&lt;SchemaVersion\&gt;2.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VS2008_Project_stg {
            get {
                return ResourceManager.GetString("VS2008_Project_stg", resourceCulture);
            }
        }
    }
}
